# Generated by Django 4.1.5 on 2023-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itapp", "0008_complaints_ack"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="reject",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
